name: XSS Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain'
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Scanning ${{ inputs.domain }}"
          echo "Test successful!"
