name: "X8 Debug Workflow"

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain (e.g., example.com)'
        required: true
        type: string
        default: 'https://bigdav.ir/test.php'
      parameter:
        description: 'Parameter to test (e.g., category)'
        required: true
        type: string
        default: 'category'
      headers:
        description: 'Custom headers (optional, e.g., "Cookie: session=abc123")'
        required: false
        type: string
        default: ''

jobs:
  debug-x8-single:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install x8 (cargo build)
        run: |
          set -euxo pipefail
          # Install Rust (if not already in environment)
          if ! command -v cargo >/dev/null 2>&1; then
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source "$HOME/.cargo/env"
          fi
          source "$HOME/.cargo/env"
          # Install x8 globally, upgrades if already installed
          cargo install --force x8
          # Add cargo bin to PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          which x8 || echo "x8 not found in PATH!"
          x8 --version || true

      - name: Debug Curl Raw Response
        run: |
          set -euxo pipefail
          echo "Debugging raw curl response for input domain: ${{ github.event.inputs.domain }}"
          echo "Testing with payload: TESTPAYLOAD"

          CURL_COMMAND="curl -k -s -X GET '${{ github.event.inputs.domain }}?${{ github.event.inputs.parameter }}=TESTPAYLOAD'"

          if [ -n "${{ github.event.inputs.headers }}" ]; then
            CURL_COMMAND="${CURL_COMMAND} -H \"${{ github.event.inputs.headers }}""
          fi

          echo "Executing curl command: $CURL_COMMAND"
          RAW_RESPONSE=$(eval "$CURL_COMMAND")
          echo "Raw Curl Response:"
          echo "$RAW_RESPONSE"

          if echo "$RAW_RESPONSE" | grep -q "TESTPAYLOAD"; then
            echo "SUCCESS: 'TESTPAYLOAD' found in raw response."
          else
            echo "WARNING: 'TESTPAYLOAD' NOT found in raw response. This might indicate no reflection."
          fi
          echo "----------------------------------------"

      - name: Run x8 with verbose output and stderr capture
        run: |
          set -euxo pipefail
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

          echo "${{ github.event.inputs.domain }}" > target_url.txt
          echo "${{ github.event.inputs.parameter }}" > param_wordlist.txt

          DEBUG_OUTPUT_DIR="x8-debug-results"
          mkdir -p "$DEBUG_OUTPUT_DIR"

          echo "Running x8 with verbose output on ${{ github.event.inputs.domain }}..."
          echo "Parameter wordlist: ${{ github.event.inputs.parameter }}"

          if [[ -s "target_url.txt" ]] && [[ -s "param_wordlist.txt" ]]; then
            # Must use full path to x8 in case cargo bin isn't sourced in non-interactive shell
            export PATH="$HOME/.cargo/bin:$PATH"
            x8 -u "$(cat target_url.txt)" -w param_wordlist.txt -v 2>&1 | tee "${DEBUG_OUTPUT_DIR}/x8-verbose.log" || true

            X8_EXIT_CODE=$?
            echo "x8 exited with code: $X8_EXIT_CODE"

            echo "--- Raw x8 Scan Output (from log file): ---"
            cat "${DEBUG_OUTPUT_DIR}/x8-verbose.log" || echo "x8-verbose.log not found or empty."
            echo "--------------------------------------------"

            if grep -q "reflections: ${{ github.event.inputs.parameter }}" "${DEBUG_OUTPUT_DIR}/x8-verbose.log"; then
              echo "SUCCESS: 'reflections: ${{ github.event.inputs.parameter }}' found in x8 output."
            else
              echo "WARNING: 'reflections: ${{ github.event.inputs.parameter }}' NOT found in x8 output."
              echo "This indicates x8 is still not reporting the reflection in CI."
            fi
          else
            echo "ERROR: Input files target_url.txt or param_wordlist.txt are empty or not found."
            touch "${DEBUG_OUTPUT_DIR}/x8-verbose.log"
          fi

      # - name: Start tmate session for live debugging (Optional)
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     ssh: true
