name: Docker Test for x8

on:
  workflow_dispatch:

jobs:
  docker-x8-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f .github/workflows/Dockerfile.test -t x8-test:latest .

      - name: Create test files
        run: |
          mkdir -p combined-results
          echo "category" > combined-results/unfurl-params.txt
          echo "id" >> combined-results/unfurl-params.txt
          echo "test" >> combined-results/unfurl-params.txt

      - name: Test x8 simple
        run: |
          docker run --rm -v "$PWD":/workspace x8-test:latest bash -c '
          cd /workspace
          echo "Testing x8..."
          x8 -u "https://bigdav.ir/test.php?category=TEST" -w combined-results/unfurl-params.txt -X GET -v
          '
