name: Docker Test for x8

on:
  workflow_dispatch:

jobs:
  docker-x8-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image using Dockerfile.test
        run: |
          # Build from the actual location of Dockerfile.test
          docker build -f .github/workflows/Dockerfile.test -t x8-test:latest .


      - name: Run Docker container and test x8
        run: |
          docker run --rm -v "${{ github.workspace }}":/workspace x8-test:latest bash -c "\
            cd /workspace && \
            echo 'Testing curl reflection...' && \
            curl -s -G --data-urlencode 'category=TESTPAYLOAD' 'https://bigdav.ir/test.php' | grep TESTPAYLOAD && echo 'Curl test OK' && \
            echo 'Testing x8 execution...' && \
            x8 -u 'https://bigdav.ir/test.php?category=TESTPAYLOAD' -w combined-results/unfurl-params.txt -X GET POST -v 2>&1 | tee x8.log && \
            grep 'reflects:' x8.log"
