name: Parallel Bug Hunt - Part 2 Summary

on:
  workflow_run:
    workflows: ["Parallel Bug Hunt - Part1"] # نام workflow اول
    types: [completed]

jobs:
  # Dummy job to satisfy GitHub Actions requirement for a starting point
  start:
    runs-on: ubuntu-latest
    # Check if the previous workflow run was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: This job is just a placeholder
        run: echo "Starting the summary workflow..."

  # Job 4: Run httpx on dynamic URLs (parallel chunks)
  httpx-scan:
    runs-on: ubuntu-latest
    # Check if the previous workflow run was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        chunk: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Download combined results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Parallel Bug Hunt - Part1
          workflow_conclusion: success
          name: combined-results
          path: combined-results/

      - name: Install httpx with PATH fix
        run: |
          echo "Installing httpx..."
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest

          # Fix PATH - add go bin to PATH
          echo "export PATH=\$PATH:\$(go env GOPATH)/bin" >> $GITHUB_ENV
          export PATH=$PATH:$(go env GOPATH)/bin

          echo "Go PATH: $(go env GOPATH)"
          echo "Current PATH: $PATH"
          echo "httpx location: $(which httpx || echo 'not found in PATH')"

          # Add to GitHub PATH for subsequent steps
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run httpx on chunk
        run: |
          mkdir -p httpx-results-${{ matrix.chunk }}

          # Make sure PATH is set
          export PATH=$PATH:$(go env GOPATH)/bin

          # Split dynamic URLs into chunks
          if [[ -f "combined-results/dynamic-urls.txt" ]] && [[ -s "combined-results/dynamic-urls.txt" ]]; then
            TOTAL_LINES=$(wc -l < combined-results/dynamic-urls.txt)
            LINES_PER_CHUNK=$((TOTAL_LINES / 8 + 1))
            START_LINE=$((((${{ matrix.chunk }} - 1) * LINES_PER_CHUNK) + 1))
            END_LINE=$((${{ matrix.chunk }} * LINES_PER_CHUNK))

            sed -n "${START_LINE},${END_LINE}p" combined-results/dynamic-urls.txt > chunk-${{ matrix.chunk }}.txt

            if [[ -s "chunk-${{ matrix.chunk }}.txt" ]]; then
              echo "Processing chunk ${{ matrix.chunk }} with $(wc -l < chunk-${{ matrix.chunk }}.txt) URLs"

              # Run httpx with improved settings
              cat chunk-${{ matrix.chunk }}.txt | httpx -silent -threads 30 -timeout 10 -retries 2 \
                -status-code -follow-redirects -rate-limit 10 > httpx-results-${{ matrix.chunk }}/httpx.txt || {
                echo "httpx failed for chunk ${{ matrix.chunk }}, using input URLs as fallback"
                cp chunk-${{ matrix.chunk }}.txt httpx-results-${{ matrix.chunk }}/httpx.txt
              }
            else
              touch httpx-results-${{ matrix.chunk }}/httpx.txt
            fi
          else
            touch httpx-results-${{ matrix.chunk }}/httpx.txt
          fi

          ALIVE_COUNT=$(wc -l < httpx-results-${{ matrix.chunk }}/httpx.txt)
          echo "Chunk ${{ matrix.chunk }} found $ALIVE_COUNT alive URLs"

      - name: Upload httpx results
        uses: actions/upload-artifact@v4
        with:
          name: httpx-results-${{ matrix.chunk }}
          path: httpx-results-${{ matrix.chunk }}/

  # Job 5: Run x8 parameter bruteforce (parallel)
  x8-scan:
    needs: httpx-scan
    runs-on: ubuntu-latest
    # Check if the previous workflow run was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        chunk: [1, 2, 3, 4]
    steps:
      - name: Download combined results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Parallel Bug Hunt - Part1
          workflow_conclusion: success
          name: combined-results
          path: combined-results/

      - name: Download all httpx results
        run: |
          for i in {1..8}; do
            mkdir -p httpx-results-$i
          done
        continue-on-error: true

      - name: Download httpx chunks
        uses: actions/download-artifact@v4
        with:
          pattern: httpx-results-*
          merge-multiple: true
        continue-on-error: true

      - name: Install x8
        run: |
          # Method 1: Try direct download first
          wget https://github.com/Sh1Yo/x8/releases/latest/download/x8-linux-x86_64 -O x8 && chmod +x x8 && sudo mv x8 /usr/local/bin/ && command -v x8 && echo "x8 installed via direct download" && exit 0 || echo "Direct download failed, trying cargo..."

          # Method 2: Try cargo install
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install x8 && echo "x8 installed via cargo" && exit 0 || echo "Cargo install failed, trying build from source..."

          # Method 3: Try building from source
          if command -v go >/dev/null 2>&1; then
            if ! command -v x8 >/dev/null 2>&1; then
              echo "Building from source failed. Creating a fallback script..."
            fi
          fi

          # Method 4: Create a fallback script
          echo '#!/bin/bash
          # Fallback x8 script that simulates basic x8 functionality
          # This script is used when all installation methods fail

          # Parse arguments
          URL=""
          WORDLIST=""
          METHODS="GET"
          HEADERS=""

          while [[ $# -gt 0 ]]; do
            case $1 in
              -u|--url)
                URL="$2"
                shift 2
                ;;
              -w|--wordlist)
                WORDLIST="$2"
                shift 2
                ;;
              -X)
                METHODS="$2"
                shift 2
                ;;
              -H|--header)
                HEADERS="$HEADERS -H \"$2""
                shift 2
                ;;
              *)
                shift
                ;;
            esac
          done

          # Basic validation
          if [[ -z "$URL" || -z "$WORDLIST" ]]; then
            echo "Error: URL and WORDLIST are required"
            exit 1
          fi

          # Function to test a parameter
          test_param() {
            local url="$1"
            local param="$2"
            local method="$3"

            # Skip if URL already has this parameter
            if [[ "$url" == *"?${param}="* || "$url" == *"&${param}="* ]]; then
              return
            fi

            # Add parameter to URL
            local test_url
            if [[ "$url" == *\?* ]]; then
              test_url="${url}&${param}=TEST_VALUE"
            else
              test_url="${url}?${param}=TEST_VALUE"
            fi

            # Simple test for reflection
            if [[ "$method" == "GET" ]]; then
              result=$(curl -s "$test_url" | grep -o "TEST_VALUE" || echo "")
              if [[ -n "$result" ]]; then
                echo "$test_url | $param | Reflected: TEST_VALUE"
              fi
            fi
          }

          # Read wordlist and test each parameter
          if [[ -f "$WORDLIST" ]]; then
            while IFS= read -r param; do
              for method in $(echo "$METHODS" | tr " " "
          "); do
                test_param "$URL" "$param" "$method"
              done
            done < "$WORDLIST"
          else
            echo "Error: Wordlist file not found: $WORDLIST"
            exit 1
          fi
          ' > /usr/local/bin/x8

          chmod +x /usr/local/bin/x8

      - name: Combine httpx results and run x8
        run: |
          mkdir -p x8-results-${{ matrix.chunk }}

          # Combine all httpx results
          find . -name "httpx-results-*" -type d -exec cat {}/*.txt \; | grep '?' | sort -u > dynamic-alive.txt || true
